import { Store, Product, Order, Integration } from '../types';

export const initialStores: Store[] = [
  {
    id: 'store-andhika',
    merchantId: 'usr-andhika-01',
    name: 'Toko Andhikagonzales',
    slug: 'toko-andhikagonzales',
    tagline: 'Pusat Produk UMKM Unggulan & Kerajinan Khas Nusantara',
    description: 'Menyediakan beragam produk UMKM berkualitas tinggi mulai dari kemeja batik premium, kopi specialty Nusantara, kerajinan kulit sapi asli, hingga kuliner khas siap kirim ke seluruh Indonesia.',
    logoUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '081234567890',
    city: 'Yogyakarta, DI Yogyakarta',
    province: 'DI Yogyakarta',
    address: 'Jl. Malioboro No. 88, Danurejan, Yogyakarta',
    category: 'Fashion, Kopi & Kerajinan UMKM',
    currency: 'IDR',
    balance: 3850000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'store-1',
    merchantId: 'usr-kirana-01',
    name: 'Toko Batik Kirana',
    slug: 'toko-batik',
    tagline: 'Koleksi Batik Tulis & Cap Asli Pekalongan dan Solo',
    description: 'Menyediakan busana batik modern, kemeja pria premium, dress wanita, dan kain batik sutra berkualitas tinggi dengan sentuhan warisan budaya Nusantara.',
    logoUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '081234567890',
    city: 'Pekalongan, Jawa Tengah',
    address: 'Jl. Hayam Wuruk No. 45, Pekalongan',
    category: 'Fashion & Pakaian Tradisional',
    currency: 'IDR',
    balance: 2450000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'store-2',
    merchantId: 'usr-barista-01',
    name: 'Kedai Kopi Nusantara',
    slug: 'kedai-kopi',
    tagline: 'Biji Kopi Specialty Single Origin Asli Petani Lokal',
    description: 'Roastery kopi lokal dengan pilihan biji kopi Arabika Gayo, Toraja, Kintamani, dan Robusta Dampit yang di-roast fresh setiap pekan.',
    logoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '082198765432',
    city: 'Bandung, Jawa Barat',
    address: 'Jl. Riau No. 112, Bandung',
    category: 'Makanan & Minuman (F&B)',
    currency: 'IDR',
    balance: 1890000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'store-3',
    merchantId: 'usr-artisan-01',
    name: 'Sepatu Kulit Garut Artisan',
    slug: 'sepatu-garut',
    tagline: 'Sepatu & Aksesoris Kulit Asli Buatan Pengrajin Garut',
    description: 'Produk handmade kulit sapi asli berkualitas ekspor. Sepatu formal, boots, dompet kulit, dan ikat pinggang dengan garansi ketahanan.',
    logoUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '085711223344',
    city: 'Garut, Jawa Barat',
    address: 'Sentra Kulit Sukaregang Blok B-12, Garut',
    category: 'Sepatu & Kerajinan Kulit',
    currency: 'IDR',
    balance: 5120000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-01-20T09:30:00Z',
  },
];

export const initialProducts: Product[] = [
  // Store 0 - Toko Andhikagonzales (Default / Primary Account)
  {
    id: 'prod-andhika-101',
    storeId: 'store-andhika',
    name: 'Kemeja Batik Tulis Modern Heritage Lengan Panjang',
    slug: 'kemeja-batik-tulis-modern-heritage',
    description: 'Kemeja batik katun primisima premium dengan motif kontemporer warisan budaya. Jahitan rapi berkantong paspol, furing trikot halus, adem dan nyaman untuk kerja maupun acara formal.',
    price: 185000,
    originalPrice: 230000,
    stock: 24,
    category: 'Fashion Pria',
    imageUrl: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'AND-BTK-01',
    weightGrams: 320,
    isFeatured: true,
    salesCount: 42,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-andhika-102',
    storeId: 'store-andhika',
    name: 'Arabika Single Origin Gayo Winey Roast 250g',
    slug: 'arabika-single-origin-gayo-winey',
    description: 'Biji kopi specialty Arabika Aceh Gayo pilihan dengan fermentasi anaerobic natural winey. Notes: Blackcurrant, plum, caramelized brown sugar, delicate body with smooth lingering finish.',
    price: 98000,
    originalPrice: 115000,
    stock: 18,
    category: 'Kopi & Minuman',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'AND-KPI-02',
    weightGrams: 270,
    isFeatured: true,
    salesCount: 88,
    createdAt: '2026-08-02T11:00:00Z',
  },
  {
    id: 'prod-andhika-103',
    storeId: 'store-andhika',
    name: 'Dompet Kulit Sapi Asli Handcrafted Bifold Minimalist',
    slug: 'dompet-kulit-sapi-handcrafted-bifold',
    description: 'Dompet pria kulit sapi CRAZY HORSE asli buatan pengrajin lokal Garut & Yogyakarta. Dilengkapi 8 slot kartu dan 2 kompartemen uang tunai. Patina kulit semakin mewah seiring pemakaian.',
    price: 175000,
    originalPrice: 210000,
    stock: 12,
    category: 'Aksesoris Kulit',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'AND-KLT-03',
    weightGrams: 160,
    isFeatured: true,
    salesCount: 29,
    createdAt: '2026-08-04T09:30:00Z',
  },
  {
    id: 'prod-andhika-104',
    storeId: 'store-andhika',
    name: 'Dress Etnik Tenun Lurik Kontemporer',
    slug: 'dress-etnik-tenun-lurik',
    description: 'Dress anggun berbahan tenun lurik ATBM Klaten dipadukan dengan katun toyobo adem. Desain modern cocok untuk casual hangout, resepsi, maupun seragam kantor.',
    price: 260000,
    originalPrice: 310000,
    stock: 8,
    category: 'Fashion Wanita',
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'AND-DRS-04',
    weightGrams: 380,
    salesCount: 15,
    createdAt: '2026-08-06T14:15:00Z',
  },
  {
    id: 'prod-andhika-105',
    storeId: 'store-andhika',
    name: 'Sambal Roa Asap Khas Nusantara Jar 200g',
    slug: 'sambal-roa-asap-nusantara-200g',
    description: 'Sambal roa asli dengan ikan roa asap premium Manado berpadu cabai rawit segar dan minyak kelapa murni. Gurih pedas nikmat tanpa bahan pengawet buatan. Halal & tersertifikasi P-IRT.',
    price: 48000,
    stock: 35,
    category: 'Kuliner & Camilan',
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'AND-FOD-05',
    weightGrams: 240,
    salesCount: 120,
    createdAt: '2026-08-08T10:00:00Z',
  },
  {
    id: 'prod-andhika-106',
    storeId: 'store-andhika',
    name: 'Tumbler Bambu Stainless Steel Grafir Etnik 500ml',
    slug: 'tumbler-bambu-stainless-steel-grafir',
    description: 'Botol minum ramah lingkungan dengan lapisan luar bambu alami berukir motif batik parang dan dinding ganda stainless steel 304 tahan panas/dingin hingga 12 jam.',
    price: 85000,
    stock: 3,
    category: 'Souvenir & Kerajinan',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
    status: 'Hampir Habis',
    sku: 'AND-TMB-06',
    weightGrams: 350,
    salesCount: 64,
    createdAt: '2026-08-10T16:00:00Z',
  },

  // Store 1 - Toko Batik Kirana
  {
    id: 'prod-101',
    storeId: 'store-1',
    name: 'Kemeja Batik Parang Premium Lengan Panjang',
    slug: 'kemeja-batik-parang-premium',
    description: 'Kemeja batik katun primisima dengan motif Parang Kusumo klasik. Dilapisi furing trikot halus, tidak panas dan nyaman dipakai untuk acara formal maupun kantor.',
    price: 175000,
    originalPrice: 225000,
    stock: 18,
    category: 'Kemeja Pria',
    imageUrl: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'BTK-PRG-01',
    weightGrams: 300,
    isFeatured: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-102',
    storeId: 'store-1',
    name: 'Dress Batik Mega Mendung Elegan',
    slug: 'dress-batik-mega-mendung',
    description: 'Dress batik modern dengan aksen Mega Mendung khas Cirebon. Model A-line anggun dengan resleting belakang tersembunyi. Bahan katun dobi lembut.',
    price: 245000,
    originalPrice: 290000,
    stock: 7,
    category: 'Dress Wanita',
    imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'BTK-DRS-02',
    weightGrams: 350,
    isFeatured: true,
    createdAt: '2026-08-03T11:30:00Z',
  },
  {
    id: 'prod-103',
    storeId: 'store-1',
    name: 'Kain Batik Tulis Sutra Motif Kawung',
    slug: 'kain-batik-tulis-sutra-kawung',
    description: 'Kain panjang batik tulis asli buatan seniman Solo. Menggunakan bahan sutra ATBM 2.5m x 1.15m. Pewarnaan alami ramah lingkungan.',
    price: 650000,
    originalPrice: 750000,
    stock: 3,
    category: 'Kain Tradisional',
    imageUrl: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&auto=format&fit=crop&q=80',
    status: 'Hampir Habis',
    sku: 'BTK-KN-03',
    weightGrams: 400,
    isFeatured: true,
    createdAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'prod-104',
    storeId: 'store-1',
    name: 'Outer Batik Etnik Tenun Casual',
    slug: 'outer-batik-etnik-tenun',
    description: 'Outerwear santai dengan kombinasi motif tenun ikat dan batik cap. Cocok dipadukan dengan celana jeans atau kulot santai.',
    price: 135000,
    stock: 14,
    category: 'Outerwear',
    imageUrl: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'BTK-OUT-04',
    weightGrams: 280,
    createdAt: '2026-08-08T14:15:00Z',
  },
  {
    id: 'prod-105',
    storeId: 'store-1',
    name: 'Scarf Selendang Batik Silk Lembut',
    slug: 'scarf-selendang-batik-silk',
    description: 'Selendang sutra halus motif sekar jagad. Cocok untuk aksesoris kebaya maupun hijab pashmina elegan.',
    price: 85000,
    stock: 0,
    category: 'Aksesoris',
    imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&auto=format&fit=crop&q=80',
    status: 'Habis',
    sku: 'BTK-SCF-05',
    weightGrams: 120,
    createdAt: '2026-08-10T16:00:00Z',
  },

  // Store 2 - Kedai Kopi Nusantara
  {
    id: 'prod-201',
    storeId: 'store-2',
    name: 'Arabika Gayo Winey Process 250gr',
    slug: 'arabika-gayo-winey-250gr',
    description: 'Kopi Arabika Aceh Gayo dengan proses fermentasi anaerobic winey. Taste notes: Fruity, grape, dried fruits, silky body, sweet lingering aftertaste.',
    price: 95000,
    originalPrice: 110000,
    stock: 25,
    category: 'Biji Kopi Arabika',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'KPI-GYO-01',
    weightGrams: 270,
    isFeatured: true,
    createdAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'prod-202',
    storeId: 'store-2',
    name: 'Drip Bag Coffee Nusantara Box (Isi 10 Sachet)',
    slug: 'drip-bag-coffee-nusantara-box',
    description: 'Paket kopi praktis tanpa ampas. Cukup tuang air panas 150ml. Mengandung 5 varian single origin terbaik Indonesia.',
    price: 80000,
    stock: 4,
    category: 'Kopi Praktis',
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
    status: 'Hampir Habis',
    sku: 'KPI-DRP-02',
    weightGrams: 200,
    isFeatured: true,
    createdAt: '2026-08-04T12:00:00Z',
  },

  // Store 3 - Sepatu Kulit Garut
  {
    id: 'prod-301',
    storeId: 'store-3',
    name: 'Oxford Leather Shoes Classic Tan',
    slug: 'oxford-leather-shoes-classic-tan',
    description: 'Sepatu pantofel pria kulit sapi pull-up asli warna Tan. Sol karet anti licin dan jahitan sol tembus kuat seumur hidup.',
    price: 480000,
    originalPrice: 550000,
    stock: 12,
    category: 'Sepatu Formal',
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'SPT-OXF-01',
    weightGrams: 950,
    isFeatured: true,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-302',
    storeId: 'store-3',
    name: 'Dompet Kulit Asli Bifold Minimalist',
    slug: 'dompet-kulit-asli-bifold',
    description: 'Dompet pria kulit sapi CRAZY HORSE leather dengan patina natural yang semakin bagus seiring pemakaian. 8 slot kartu dan 2 slot uang.',
    price: 165000,
    stock: 22,
    category: 'Aksesoris Kulit',
    imageUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
    status: 'Tersedia',
    sku: 'SPT-DMP-02',
    weightGrams: 150,
    createdAt: '2026-08-03T11:00:00Z',
  },
];

export const initialOrders: Order[] = [
  // Store 0 - Toko Andhikagonzales Orders
  {
    id: 'ord-andhika-101',
    storeId: 'store-andhika',
    orderNumber: 'KB-9042',
    customerName: 'Bagus Wicaksono',
    customerPhone: '081239847112',
    customerEmail: 'bagus.wicaksono@gmail.com',
    customerAddress: 'Jl. Gejayan No. 42, Sleman',
    customerCity: 'Kab. Sleman, DI Yogyakarta',
    customerPostalCode: '55281',
    items: [
      {
        productId: 'prod-andhika-101',
        productName: 'Kemeja Batik Tulis Modern Heritage Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 185000,
        quantity: 2,
        subtotal: 370000,
        variantName: 'Size L',
      },
      {
        productId: 'prod-andhika-102',
        productName: 'Arabika Single Origin Gayo Winey Roast 250g',
        productImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
        price: 98000,
        quantity: 1,
        subtotal: 98000,
        variantName: 'Biji (Whole Beans)',
      },
    ],
    subtotal: 468000,
    shippingCost: 12000,
    discount: 20000,
    grandTotal: 460000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'SiCepat',
    courierService: 'BEST Sameday',
    resiNumber: '003921849102',
    shippingStatus: 'Diproses',
    createdAt: '2026-08-27T10:30:00Z',
    notes: 'Kemeja tolong dicek kancing cadangannya ya kak. Terima kasih!',
  },
  {
    id: 'ord-andhika-102',
    storeId: 'store-andhika',
    orderNumber: 'KB-9041',
    customerName: 'Siti Rahmadani',
    customerPhone: '085811223399',
    customerEmail: 'siti.rahma@yahoo.com',
    customerAddress: 'Jl. R.E. Martadinata No. 104, Riau',
    customerCity: 'Kota Bandung, Jawa Barat',
    customerPostalCode: '40115',
    items: [
      {
        productId: 'prod-andhika-104',
        productName: 'Dress Etnik Tenun Lurik Kontemporer',
        productImage: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
        price: 260000,
        quantity: 1,
        subtotal: 260000,
        variantName: 'Size M - Navy',
      },
      {
        productId: 'prod-andhika-105',
        productName: 'Sambal Roa Asap Khas Nusantara Jar 200g',
        productImage: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
        price: 48000,
        quantity: 2,
        subtotal: 96000,
      },
    ],
    subtotal: 356000,
    shippingCost: 18000,
    discount: 0,
    grandTotal: 374000,
    paymentMethod: 'BCA_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'J&T',
    courierService: 'EZ Regular (1-2 Hari)',
    resiNumber: 'JT9928172635',
    shippingStatus: 'Dikirim',
    createdAt: '2026-08-26T15:20:00Z',
    shippedAt: '2026-08-27T08:30:00Z',
    notes: 'Mohon bubble wrap tebal untuk botol sambal roa.',
  },
  {
    id: 'ord-andhika-103',
    storeId: 'store-andhika',
    orderNumber: 'KB-9040',
    customerName: 'Dimas Aditya',
    customerPhone: '081799887766',
    customerEmail: 'dimas.aditya@techcorp.id',
    customerAddress: 'Menara BTPN Lt 24, Mega Kuningan',
    customerCity: 'Jakarta Selatan, DKI Jakarta',
    customerPostalCode: '12950',
    items: [
      {
        productId: 'prod-andhika-103',
        productName: 'Dompet Kulit Sapi Asli Handcrafted Bifold Minimalist',
        productImage: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
        price: 175000,
        quantity: 1,
        subtotal: 175000,
        variantName: 'Crazy Horse Tan',
      },
      {
        productId: 'prod-andhika-106',
        productName: 'Tumbler Bambu Stainless Steel Grafir Etnik 500ml',
        productImage: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
        price: 85000,
        quantity: 1,
        subtotal: 85000,
      },
    ],
    subtotal: 260000,
    shippingCost: 25000,
    discount: 0,
    grandTotal: 285000,
    paymentMethod: 'MANDIRI_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'GoSend',
    courierService: 'Instant Delivery',
    resiNumber: 'GK-881920',
    shippingStatus: 'Selesai',
    createdAt: '2026-08-25T11:00:00Z',
    shippedAt: '2026-08-25T13:15:00Z',
  },
  {
    id: 'ord-andhika-104',
    storeId: 'store-andhika',
    orderNumber: 'KB-9039',
    customerName: 'Priscilia Tan',
    customerPhone: '081288990011',
    customerEmail: 'priscilia.t@gmail.com',
    customerAddress: 'Cluster Gardenia Blok E No. 9, Gading Serpong',
    customerCity: 'Kab. Tangerang, Banten',
    customerPostalCode: '15810',
    items: [
      {
        productId: 'prod-andhika-101',
        productName: 'Kemeja Batik Tulis Modern Heritage Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 185000,
        quantity: 1,
        subtotal: 185000,
        variantName: 'Size M',
      },
    ],
    subtotal: 185000,
    shippingCost: 15000,
    discount: 0,
    grandTotal: 200000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'JNE',
    courierService: 'REG (1-2 Hari)',
    resiNumber: '',
    shippingStatus: 'Baru',
    createdAt: '2026-08-27T18:45:00Z',
    notes: 'Pesanan baru masuk via QRIS Dinamis Toko.',
  },

  // Store 1 - Toko Batik Kirana
  {
    id: 'ord-1001',
    storeId: 'store-1',
    orderNumber: 'KB-8921',
    customerName: 'Alya Permata',
    customerPhone: '081298761234',
    customerAddress: 'Jl. Melati No. 18, Menteng',
    customerCity: 'Jakarta Pusat',
    items: [
      {
        productId: 'prod-101',
        productName: 'Kemeja Batik Parang Premium Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 175000,
        quantity: 2,
        subtotal: 350000,
        variantName: 'Size XL',
      },
    ],
    subtotal: 350000,
    shippingCost: 15000,
    discount: 0,
    grandTotal: 365000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'J&T',
    courierService: 'EZ Regular (1-2 Hari)',
    resiNumber: '',
    shippingStatus: 'Baru',
    createdAt: '2026-08-17T14:30:00Z',
    notes: 'Tolong packing rapi ya, untuk kado ulang tahun.',
  },
  {
    id: 'ord-1002',
    storeId: 'store-1',
    orderNumber: 'KB-8920',
    customerName: 'Budi Santoso',
    customerPhone: '081344556677',
    customerAddress: 'Komp. Graha Indah Blok C-4',
    customerCity: 'Surabaya',
    items: [
      {
        productId: 'prod-102',
        productName: 'Dress Batik Mega Mendung Elegan',
        productImage: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
        price: 245000,
        quantity: 1,
        subtotal: 245000,
      },
      {
        productId: 'prod-104',
        productName: 'Outer Batik Etnik Tenun Casual',
        productImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
        price: 135000,
        quantity: 1,
        subtotal: 135000,
      },
    ],
    subtotal: 380000,
    shippingCost: 18000,
    discount: 20000,
    grandTotal: 378000,
    paymentMethod: 'BCA_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'SiCepat',
    courierService: 'BEST Sameday',
    resiNumber: '003291882190',
    shippingStatus: 'Diproses',
    createdAt: '2026-08-17T11:15:00Z',
  },
  {
    id: 'ord-1003',
    storeId: 'store-1',
    orderNumber: 'KB-8919',
    customerName: 'Dewi Anggraini',
    customerPhone: '087855667788',
    customerAddress: 'Jl. Dago Asri V No. 8',
    customerCity: 'Bandung',
    items: [
      {
        productId: 'prod-103',
        productName: 'Kain Batik Tulis Sutra Motif Kawung',
        productImage: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&auto=format&fit=crop&q=80',
        price: 650000,
        quantity: 1,
        subtotal: 650000,
      },
    ],
    subtotal: 650000,
    shippingCost: 14000,
    discount: 0,
    grandTotal: 664000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'JNE',
    courierService: 'REG (1-2 Hari)',
    resiNumber: 'JNE8829104523',
    shippingStatus: 'Dikirim',
    createdAt: '2026-08-16T16:45:00Z',
    shippedAt: '2026-08-17T09:00:00Z',
  },
  {
    id: 'ord-1004',
    storeId: 'store-1',
    orderNumber: 'KB-8918',
    customerName: 'Hendra Pratama',
    customerPhone: '081900112233',
    customerAddress: 'Apartemen Sudirman Tower A Lt 12',
    customerCity: 'Jakarta Selatan',
    items: [
      {
        productId: 'prod-101',
        productName: 'Kemeja Batik Parang Premium Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 175000,
        quantity: 1,
        subtotal: 175000,
      },
    ],
    subtotal: 175000,
    shippingCost: 25000,
    discount: 0,
    grandTotal: 200000,
    paymentMethod: 'MANDIRI_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'GoSend',
    courierService: 'Instant Delivery',
    resiNumber: 'GK-992144',
    shippingStatus: 'Selesai',
    createdAt: '2026-08-15T10:10:00Z',
  },
];

export const initialIntegrations: Integration[] = [
  // Payments
  {
    id: 'int-midtrans',
    type: 'payment',
    provider: 'midtrans',
    name: 'Midtrans Payment Gateway',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=80',
    description: 'Terima pembayaran otomatis dari 20+ bank via Virtual Account, GoPay, ShopeePay, dan Kartu Kredit.',
    isConnected: true,
    isPopular: true,
    statusText: 'Terhubung & Aktif',
    config: {
      merchantId: 'M0892819',
      clientKey: 'Mid-client-88192019',
      environment: 'production',
    },
  },
  {
    id: 'int-qris',
    type: 'payment',
    provider: 'qris',
    name: 'QRIS Statis & Dinamis Instant',
    logo: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=100&auto=format&fit=crop&q=80',
    description: 'Scan & bayar langsung dari semua e-wallet (BCA, Mandiri, GoPay, OVO, DANA, LinkAja) dengan MDR 0.7%.',
    isConnected: true,
    isPopular: true,
    statusText: 'Terhubung & Aktif',
  },
  {
    id: 'int-stripe',
    type: 'payment',
    provider: 'stripe',
    name: 'Stripe International Card',
    logo: 'https://images.unsplash.com/photo-1556742049-0a67e5572293?w=100&auto=format&fit=crop&q=80',
    description: 'Terima pembayaran kartu kredit & debit internasional (Visa, Mastercard, AMEX) untuk ekspor produk.',
    isConnected: true,
    statusText: 'Terhubung & Aktif',
    config: {
      apiKey: 'pk_live_51M089281928340192',
      environment: 'production',
    },
  },

  // Shipping
  {
    id: 'int-jnt',
    type: 'shipping',
    provider: 'jnt',
    name: 'J&T Express Auto Resi',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=80',
    description: 'Kirim paket dengan jemput gratis (pick-up) ke toko dan resi otomatis tanpa perlu input manual.',
    isConnected: true,
    isPopular: true,
    statusText: 'Terhubung (Auto Pick-up Aktif)',
  },
  {
    id: 'int-jne',
    type: 'shipping',
    provider: 'jne',
    name: 'JNE Express Logistics',
    logo: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=100&auto=format&fit=crop&q=80',
    description: 'Jaringan pengiriman terluas ke pelosok Indonesia dengan layanan REG, YES (Yakin Esok Sampai), dan JTR Trucking.',
    isConnected: true,
    statusText: 'Terhubung',
  },
  {
    id: 'int-sicepat',
    type: 'shipping',
    provider: 'sicepat',
    name: 'SiCepat Ekspres',
    logo: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=100&auto=format&fit=crop&q=80',
    description: 'Pengiriman cepat dengan tarif flat HALU dan layanan BEST sameday untuk kota-kota besar.',
    isConnected: true,
    statusText: 'Terhubung',
  },
  {
    id: 'int-gosend',
    type: 'shipping',
    provider: 'gosend',
    name: 'GoSend Instant & Sameday',
    logo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=100&auto=format&fit=crop&q=80',
    description: 'Kurir motor instan sampai dalam 1-2 jam untuk pelanggan satu kota/wilayah.',
    isConnected: true,
    statusText: 'Terhubung',
  },
  {
    id: 'int-biteship',
    type: 'shipping',
    provider: 'biteship',
    name: 'Biteship Aggregator API',
    logo: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=100&auto=format&fit=crop&q=80',
    description: 'Satu integrasi untuk 25+ ekspedisi sekaligus (Anteraja, Lion Parcel, Ninja Van, Pos Indonesia, dll).',
    isConnected: false,
    statusText: 'Belum terhubung',
  },
];
