import { Store, Product, Order, Integration } from '../types';

export const initialStores: Store[] = [
  {
    id: 'store-andhika',
    merchantId: 'usr-andhika-01',
    name: 'Toko Andhikagonzales',
    slug: 'toko-andhikagonzales',
    tagline: 'Pusat Produk UMKM Unggulan & Kerajinan Khas Nusantara',
    description: 'Menyediakan beragam produk UMKM berkualitas tinggi mulai dari kemeja batik premium, kopi specialty Nusantara, kerajinan kulit sapi asli, hingga kuliner khas siap kirim ke seluruh Indonesia.',
    logoUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '081234567890',
    city: 'Yogyakarta, DI Yogyakarta',
    province: 'DI Yogyakarta',
    address: 'Jl. Malioboro No. 88, Danurejan, Yogyakarta',
    category: 'Fashion, Kopi & Kerajinan UMKM',
    currency: 'IDR',
    balance: 3850000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'store-1',
    merchantId: 'usr-kirana-01',
    name: 'Toko Batik Kirana',
    slug: 'toko-batik',
    tagline: 'Koleksi Batik Tulis & Cap Asli Pekalongan dan Solo',
    description: 'Menyediakan busana batik modern, kemeja pria premium, dress wanita, dan kain batik sutra berkualitas tinggi dengan sentuhan warisan budaya Nusantara.',
    logoUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '081234567890',
    city: 'Pekalongan, Jawa Tengah',
    address: 'Jl. Hayam Wuruk No. 45, Pekalongan',
    category: 'Fashion & Pakaian Tradisional',
    currency: 'IDR',
    balance: 2450000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'store-2',
    merchantId: 'usr-barista-01',
    name: 'Kedai Kopi Nusantara',
    slug: 'kedai-kopi',
    tagline: 'Biji Kopi Specialty Single Origin Asli Petani Lokal',
    description: 'Roastery kopi lokal dengan pilihan biji kopi Arabika Gayo, Toraja, Kintamani, dan Robusta Dampit yang di-roast fresh setiap pekan.',
    logoUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '082198765432',
    city: 'Bandung, Jawa Barat',
    address: 'Jl. Riau No. 112, Bandung',
    category: 'Makanan & Minuman (F&B)',
    currency: 'IDR',
    balance: 1890000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'store-3',
    merchantId: 'usr-artisan-01',
    name: 'Sepatu Kulit Garut Artisan',
    slug: 'sepatu-garut',
    tagline: 'Sepatu & Aksesoris Kulit Asli Buatan Pengrajin Garut',
    description: 'Produk handmade kulit sapi asli berkualitas ekspor. Sepatu formal, boots, dompet kulit, dan ikat pinggang dengan garansi ketahanan.',
    logoUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=200&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&auto=format&fit=crop&q=80',
    phoneWhatsApp: '085711223344',
    city: 'Garut, Jawa Barat',
    address: 'Sentra Kulit Sukaregang Blok B-12, Garut',
    category: 'Sepatu & Kerajinan Kulit',
    currency: 'IDR',
    balance: 5120000,
    onboarding: {
      storeNameSet: true,
      productUploaded: true,
      paymentConnected: true,
    },
    createdAt: '2026-01-20T09:30:00Z',
  },
];

export const initialProducts: Product[] = [];

export const initialOrders: Order[] = [
  // Order Baru untuk Uji Coba Pengiriman - Telkom University Bandung
  {
    id: 'ord-utiy-telkom-2026',
    storeId: 'store-andhika',
    orderNumber: 'KB-9901',
    customerName: 'utiy',
    customerPhone: '081223344556',
    customerEmail: 'utiy@telkomuniversity.ac.id',
    customerAddress: 'Gedung Asrama Putri / Gedung Pelangi, Telkom University, Jl. Telekomunikasi No. 1, Terusan Buahbatu, Sukapura, Kec. Dayeuhkolot',
    customerCity: 'Kab. Bandung, Jawa Barat',
    customerPostalCode: '40257',
    items: [
      {
        productId: 'prod-andhika-101',
        productName: 'Kemeja Batik Tulis Modern Heritage Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 185000,
        quantity: 1,
        subtotal: 185000,
        variantName: 'Size M',
      },
    ],
    subtotal: 185000,
    shippingCost: 14000,
    discount: 0,
    grandTotal: 199000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'J&T',
    courierService: 'EZ Regular (1-2 Hari)',
    resiNumber: '',
    shippingStatus: 'Baru',
    createdAt: new Date().toISOString(),
    notes: 'Kirim ke pos satpam / lobi asrama Telkom University. Tolong hubungi nomor WA sebelum sampai.',
  },
  // Store 0 - Toko Andhikagonzales Orders
  {
    id: 'ord-andhika-101',
    storeId: 'store-andhika',
    orderNumber: 'KB-9042',
    customerName: 'Bagus Wicaksono',
    customerPhone: '081239847112',
    customerEmail: 'bagus.wicaksono@gmail.com',
    customerAddress: 'Jl. Gejayan No. 42, Sleman',
    customerCity: 'Kab. Sleman, DI Yogyakarta',
    customerPostalCode: '55281',
    items: [
      {
        productId: 'prod-andhika-101',
        productName: 'Kemeja Batik Tulis Modern Heritage Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 185000,
        quantity: 2,
        subtotal: 370000,
        variantName: 'Size L',
      },
      {
        productId: 'prod-andhika-102',
        productName: 'Arabika Single Origin Gayo Winey Roast 250g',
        productImage: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
        price: 98000,
        quantity: 1,
        subtotal: 98000,
        variantName: 'Biji (Whole Beans)',
      },
    ],
    subtotal: 468000,
    shippingCost: 12000,
    discount: 20000,
    grandTotal: 460000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'SiCepat',
    courierService: 'BEST Sameday',
    resiNumber: '003921849102',
    shippingStatus: 'Diproses',
    createdAt: '2026-08-27T10:30:00Z',
    notes: 'Kemeja tolong dicek kancing cadangannya ya kak. Terima kasih!',
  },
  {
    id: 'ord-andhika-102',
    storeId: 'store-andhika',
    orderNumber: 'KB-9041',
    customerName: 'Siti Rahmadani',
    customerPhone: '085811223399',
    customerEmail: 'siti.rahma@yahoo.com',
    customerAddress: 'Jl. R.E. Martadinata No. 104, Riau',
    customerCity: 'Kota Bandung, Jawa Barat',
    customerPostalCode: '40115',
    items: [
      {
        productId: 'prod-andhika-104',
        productName: 'Dress Etnik Tenun Lurik Kontemporer',
        productImage: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
        price: 260000,
        quantity: 1,
        subtotal: 260000,
        variantName: 'Size M - Navy',
      },
      {
        productId: 'prod-andhika-105',
        productName: 'Sambal Roa Asap Khas Nusantara Jar 200g',
        productImage: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
        price: 48000,
        quantity: 2,
        subtotal: 96000,
      },
    ],
    subtotal: 356000,
    shippingCost: 18000,
    discount: 0,
    grandTotal: 374000,
    paymentMethod: 'BCA_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'J&T',
    courierService: 'EZ Regular (1-2 Hari)',
    resiNumber: 'JT9928172635',
    shippingStatus: 'Dikirim',
    createdAt: '2026-08-26T15:20:00Z',
    shippedAt: '2026-08-27T08:30:00Z',
    notes: 'Mohon bubble wrap tebal untuk botol sambal roa.',
  },
  {
    id: 'ord-andhika-103',
    storeId: 'store-andhika',
    orderNumber: 'KB-9040',
    customerName: 'Dimas Aditya',
    customerPhone: '081799887766',
    customerEmail: 'dimas.aditya@techcorp.id',
    customerAddress: 'Menara BTPN Lt 24, Mega Kuningan',
    customerCity: 'Jakarta Selatan, DKI Jakarta',
    customerPostalCode: '12950',
    items: [
      {
        productId: 'prod-andhika-103',
        productName: 'Dompet Kulit Sapi Asli Handcrafted Bifold Minimalist',
        productImage: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
        price: 175000,
        quantity: 1,
        subtotal: 175000,
        variantName: 'Crazy Horse Tan',
      },
      {
        productId: 'prod-andhika-106',
        productName: 'Tumbler Bambu Stainless Steel Grafir Etnik 500ml',
        productImage: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
        price: 85000,
        quantity: 1,
        subtotal: 85000,
      },
    ],
    subtotal: 260000,
    shippingCost: 25000,
    discount: 0,
    grandTotal: 285000,
    paymentMethod: 'MANDIRI_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'GoSend',
    courierService: 'Instant Delivery',
    resiNumber: 'GK-881920',
    shippingStatus: 'Selesai',
    createdAt: '2026-08-25T11:00:00Z',
    shippedAt: '2026-08-25T13:15:00Z',
  },
  {
    id: 'ord-andhika-104',
    storeId: 'store-andhika',
    orderNumber: 'KB-9039',
    customerName: 'Priscilia Tan',
    customerPhone: '081288990011',
    customerEmail: 'priscilia.t@gmail.com',
    customerAddress: 'Cluster Gardenia Blok E No. 9, Gading Serpong',
    customerCity: 'Kab. Tangerang, Banten',
    customerPostalCode: '15810',
    items: [
      {
        productId: 'prod-andhika-101',
        productName: 'Kemeja Batik Tulis Modern Heritage Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 185000,
        quantity: 1,
        subtotal: 185000,
        variantName: 'Size M',
      },
    ],
    subtotal: 185000,
    shippingCost: 15000,
    discount: 0,
    grandTotal: 200000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'JNE',
    courierService: 'REG (1-2 Hari)',
    resiNumber: '',
    shippingStatus: 'Baru',
    createdAt: '2026-08-27T18:45:00Z',
    notes: 'Pesanan baru masuk via QRIS Dinamis Toko.',
  },

  // Store 1 - Toko Batik Kirana
  {
    id: 'ord-1001',
    storeId: 'store-1',
    orderNumber: 'KB-8921',
    customerName: 'Alya Permata',
    customerPhone: '081298761234',
    customerAddress: 'Jl. Melati No. 18, Menteng',
    customerCity: 'Jakarta Pusat',
    items: [
      {
        productId: 'prod-101',
        productName: 'Kemeja Batik Parang Premium Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 175000,
        quantity: 2,
        subtotal: 350000,
        variantName: 'Size XL',
      },
    ],
    subtotal: 350000,
    shippingCost: 15000,
    discount: 0,
    grandTotal: 365000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'J&T',
    courierService: 'EZ Regular (1-2 Hari)',
    resiNumber: '',
    shippingStatus: 'Baru',
    createdAt: '2026-08-17T14:30:00Z',
    notes: 'Tolong packing rapi ya, untuk kado ulang tahun.',
  },
  {
    id: 'ord-1002',
    storeId: 'store-1',
    orderNumber: 'KB-8920',
    customerName: 'Budi Santoso',
    customerPhone: '081344556677',
    customerAddress: 'Komp. Graha Indah Blok C-4',
    customerCity: 'Surabaya',
    items: [
      {
        productId: 'prod-102',
        productName: 'Dress Batik Mega Mendung Elegan',
        productImage: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80',
        price: 245000,
        quantity: 1,
        subtotal: 245000,
      },
      {
        productId: 'prod-104',
        productName: 'Outer Batik Etnik Tenun Casual',
        productImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80',
        price: 135000,
        quantity: 1,
        subtotal: 135000,
      },
    ],
    subtotal: 380000,
    shippingCost: 18000,
    discount: 20000,
    grandTotal: 378000,
    paymentMethod: 'BCA_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'SiCepat',
    courierService: 'BEST Sameday',
    resiNumber: '003291882190',
    shippingStatus: 'Diproses',
    createdAt: '2026-08-17T11:15:00Z',
  },
  {
    id: 'ord-1003',
    storeId: 'store-1',
    orderNumber: 'KB-8919',
    customerName: 'Dewi Anggraini',
    customerPhone: '087855667788',
    customerAddress: 'Jl. Dago Asri V No. 8',
    customerCity: 'Bandung',
    items: [
      {
        productId: 'prod-103',
        productName: 'Kain Batik Tulis Sutra Motif Kawung',
        productImage: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&auto=format&fit=crop&q=80',
        price: 650000,
        quantity: 1,
        subtotal: 650000,
      },
    ],
    subtotal: 650000,
    shippingCost: 14000,
    discount: 0,
    grandTotal: 664000,
    paymentMethod: 'QRIS',
    paymentStatus: 'Sudah Dibayar',
    courier: 'JNE',
    courierService: 'REG (1-2 Hari)',
    resiNumber: 'JNE8829104523',
    shippingStatus: 'Dikirim',
    createdAt: '2026-08-16T16:45:00Z',
    shippedAt: '2026-08-17T09:00:00Z',
  },
  {
    id: 'ord-1004',
    storeId: 'store-1',
    orderNumber: 'KB-8918',
    customerName: 'Hendra Pratama',
    customerPhone: '081900112233',
    customerAddress: 'Apartemen Sudirman Tower A Lt 12',
    customerCity: 'Jakarta Selatan',
    items: [
      {
        productId: 'prod-101',
        productName: 'Kemeja Batik Parang Premium Lengan Panjang',
        productImage: 'https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80',
        price: 175000,
        quantity: 1,
        subtotal: 175000,
      },
    ],
    subtotal: 175000,
    shippingCost: 25000,
    discount: 0,
    grandTotal: 200000,
    paymentMethod: 'MANDIRI_VA',
    paymentStatus: 'Sudah Dibayar',
    courier: 'GoSend',
    courierService: 'Instant Delivery',
    resiNumber: 'GK-992144',
    shippingStatus: 'Selesai',
    createdAt: '2026-08-15T10:10:00Z',
  },
];

export const initialIntegrations: Integration[] = [
  // Payments
  {
    id: 'int-midtrans',
    type: 'payment',
    provider: 'midtrans',
    name: 'Midtrans Payment Gateway',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=80',
    description: 'Terima pembayaran otomatis dari 20+ bank via Virtual Account, GoPay, ShopeePay, dan Kartu Kredit.',
    isConnected: true,
    isPopular: true,
    statusText: 'Terhubung & Aktif',
    config: {
      merchantId: 'M0892819',
      clientKey: 'Mid-client-88192019',
      environment: 'production',
    },
  },
  {
    id: 'int-qris',
    type: 'payment',
    provider: 'qris',
    name: 'QRIS Statis & Dinamis Instant',
    logo: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=100&auto=format&fit=crop&q=80',
    description: 'Scan & bayar langsung dari semua e-wallet (BCA, Mandiri, GoPay, OVO, DANA, LinkAja) dengan MDR 0.7%.',
    isConnected: true,
    isPopular: true,
    statusText: 'Terhubung & Aktif',
  },
  {
    id: 'int-stripe',
    type: 'payment',
    provider: 'stripe',
    name: 'Stripe International Card',
    logo: 'https://images.unsplash.com/photo-1556742049-0a67e5572293?w=100&auto=format&fit=crop&q=80',
    description: 'Terima pembayaran kartu kredit & debit internasional (Visa, Mastercard, AMEX) untuk ekspor produk.',
    isConnected: true,
    statusText: 'Terhubung & Aktif',
    config: {
      apiKey: 'pk_live_51M089281928340192',
      environment: 'production',
    },
  },

  // Shipping (Biteship Aggregator Powered)
  {
    id: 'int-jnt',
    type: 'shipping',
    provider: 'jnt',
    name: 'J&T Express Auto Resi',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=80',
    description: 'Kirim paket dengan jemput gratis (pick-up) ke toko dan resi otomatis tanpa perlu input manual.',
    isConnected: true,
    isPopular: true,
    statusText: 'Terhubung (Auto Pick-up)',
    config: {
      enabledServices: ['ez', 'super', 'economy'],
      autoInsurance: false,
      defaultHandoff: 'pickup',
    },
  },
  {
    id: 'int-jne',
    type: 'shipping',
    provider: 'jne',
    name: 'JNE Express Logistics',
    logo: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=100&auto=format&fit=crop&q=80',
    description: 'Jaringan pengiriman terluas ke pelosok Indonesia dengan layanan REG, YES (Yakin Esok Sampai), dan JTR Trucking.',
    isConnected: true,
    statusText: 'Terhubung (Drop & Pick-up)',
    config: {
      enabledServices: ['reg', 'yes', 'jtr'],
      autoInsurance: false,
      defaultHandoff: 'drop_off',
    },
  },
  {
    id: 'int-sicepat',
    type: 'shipping',
    provider: 'sicepat',
    name: 'SiCepat Ekspres',
    logo: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=100&auto=format&fit=crop&q=80',
    description: 'Pengiriman cepat dengan tarif flat HALU, SIUNTUNG, dan layanan BEST sameday untuk kota-kota besar.',
    isConnected: true,
    statusText: 'Terhubung (Pick-up Cepat)',
    config: {
      enabledServices: ['halu', 'siuntung', 'best'],
      autoInsurance: false,
      defaultHandoff: 'pickup',
    },
  },
  {
    id: 'int-gosend',
    type: 'shipping',
    provider: 'gosend',
    name: 'GoSend Instant & Sameday',
    logo: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=100&auto=format&fit=crop&q=80',
    description: 'Kurir motor instan sampai dalam 1-2 jam untuk pelanggan satu kota/wilayah.',
    isConnected: true,
    statusText: 'Terhubung (Instant)',
    config: {
      enabledServices: ['instant', 'sameday'],
      autoInsurance: true,
      defaultHandoff: 'pickup',
    },
  },
  {
    id: 'int-biteship',
    type: 'shipping',
    provider: 'biteship',
    name: 'Biteship Aggregator API',
    logo: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=100&auto=format&fit=crop&q=80',
    description: 'Gateway terpusat untuk 25+ ekspedisi sekaligus (J&T, JNE, SiCepat, Anteraja, GoSend, POS, dll).',
    isConnected: true,
    statusText: 'Terhubung via .env',
    config: {
      environment: 'production',
    },
  },
];
